
_target_: umi_day.train_network.model.progression_net.ProgressionNet

shape_meta: ${shape_meta}

# noise_scheduler:
#   _target_: diffusers.DDIMScheduler
#   num_train_timesteps: 50
#   beta_start: 0.0001
#   beta_end: 0.02
#   # beta_schedule is important
#   # this is the best we found
#   beta_schedule: squaredcos_cap_v2
#   clip_sample: True
#   set_alpha_to_one: True
#   steps_offset: 0
#   prediction_type: epsilon # or sample

hidden_dims: [1024, 512, 256, 128, 64]

obs_encoder:
  _target_: umi_day.train_network.model.vision.timm_obs_encoder.TimmObsEncoder
  shape_meta: ${shape_meta}

  ##### from scratch #####
  # model_name: 'vit_base_patch16_224'
  # model_name: 'resnet34'
  # model_name: 'vit_tiny_patch16_224'
  # model_name: 'efficientnet_b0'
  # model_name: 'efficientnet_b3'
  # pretrained: False
  # frozen: False

  ##### from scratch #####
  # model_name: 'resnet34.a1_in1k'
  model_name: 'vit_base_patch16_clip_224.openai'
  # model_name: 'convnext_base.clip_laion2b_augreg_ft_in12k'
  pretrained: True
  frozen: False

  
  global_pool: ''

  # 'avg' or 'max' or 'soft_attention' or 'spatial_embedding' or 'transformer' or 'attention_pool_2d'
  feature_aggregation: 'attention_pool_2d'
  # feature_aggregation: null
  position_encording: 'sinusoidal' # 'learnable' or 'sinusoidal'. it only works for transformer

  # it only works for resnet. 32 (7x7) or 16 (14x14)
  downsample_ratio: 32

  eval_transforms: ${...task.eval_image_transforms}

  use_group_norm: True
  share_rgb_model: False
  imagenet_norm: True

num_inference_steps: 16
obs_as_global_cond: True
diffusion_step_embed_dim: 128
down_dims: [256,512,1024]
kernel_size: 5
n_groups: 8
cond_predict_scale: True
input_pertub: 0.1 # reference: https://github.com/forever208/DDPM-IP
# train multiple diffusion steps per obs encoder forward pass
# doing this too much will cause instability!
train_diffusion_n_samples: 1
