name: singletask_umi_policy

camera_obs_latency: 0.125
robot_obs_latency: 0.0001
gripper_obs_latency: 0.02
dataset_frequeny: 0 #59.94
obs_down_sample_steps: 3 # relative to 60Hz data collection for all data except ultrawide
ultrawide_down_sample_steps: 1 # relative to 10Hz data collection of ultrawide

low_dim_obs_horizon: 2
img_obs_horizon: 2
action_horizon: 16
ignore_proprioception: False

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    camera0_main_rgb:
      shape: [3, 224, 224]
      horizon: ${task.img_obs_horizon} # int
      latency_steps: 0 # float
      down_sample_steps: ${task.obs_down_sample_steps} # int
      type: rgb
      ignore_by_policy: False
    camera0_ultrawide_rgb:
      shape: [3, 224, 224]
      horizon: ${task.img_obs_horizon} # int
      latency_steps: 0 # float
      down_sample_steps: ${task.ultrawide_down_sample_steps} # int
      type: rgb
      ignore_by_policy: False
    robot0_eef_pos:
      shape: [3]
      horizon: ${task.low_dim_obs_horizon} # int
      latency_steps: ${eval:'(${task.camera_obs_latency} - ${task.robot_obs_latency}) * ${task.dataset_frequeny}'} # float
      down_sample_steps: ${task.obs_down_sample_steps} # float
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}
    # robot0_eef_pos_abs:
    #   shape: [1]
    #   axis: [2] # 2 means z-axis
    #   horizon: ${task.low_dim_obs_horizon} # int
    #   latency_steps: ${eval:'(${task.camera_obs_latency} - ${task.robot_obs_latency}) * ${task.dataset_frequeny}'} # float
    #   down_sample_steps: ${task.obs_down_sample_steps} # float
    #   type: low_dim
    # robot0_eef_rot_axis_angle_abs:
    #   shape: [2]
    #   axis: [0, 1] # yaw and pitch
    #   horizon: ${task.low_dim_obs_horizon} # int
    #   latency_steps: ${eval:'(${task.camera_obs_latency} - ${task.robot_obs_latency}) * ${task.dataset_frequeny}'} # float
    #   down_sample_steps: ${task.obs_down_sample_steps} # float
    #   type: low_dim
    robot0_eef_rot_axis_angle:
      raw_shape: [3]
      shape: [6]
      horizon: ${task.low_dim_obs_horizon} # int
      latency_steps: ${eval:'(${task.camera_obs_latency} - ${task.robot_obs_latency}) * ${task.dataset_frequeny}'} # float
      down_sample_steps: ${task.obs_down_sample_steps} # float
      type: low_dim
      rotation_rep: rotation_6d
      ignore_by_policy: ${task.ignore_proprioception}
    robot0_gripper_width:
      shape: [1]
      horizon: ${task.low_dim_obs_horizon} # int
      latency_steps: ${eval:'(${task.camera_obs_latency} - ${task.gripper_obs_latency}) * ${task.dataset_frequeny}'} # float
      down_sample_steps: ${task.obs_down_sample_steps} # float
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}

    # pose with respect to episode start
    # robot0_eef_pos_wrt_start:
    #   shape: [3]
    #   horizon: ${task.low_dim_obs_horizon} # int
    #   latency_steps: ${eval:'(${task.camera_obs_latency} - ${task.robot_obs_latency}) * ${task.dataset_frequeny}'} # float
    #   down_sample_steps: ${task.obs_down_sample_steps} # float
    #   type: low_dim
    #   ignore_by_policy: ${task.ignore_proprioception}
    robot0_eef_rot_axis_angle_wrt_start:
      raw_shape: [3]
      shape: [6]
      horizon: ${task.low_dim_obs_horizon} # int
      latency_steps: ${eval:'(${task.camera_obs_latency} - ${task.robot_obs_latency}) * ${task.dataset_frequeny}'} # float
      down_sample_steps: ${task.obs_down_sample_steps} # float
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}
  action: 
    shape: [10]
    horizon: ${task.action_horizon}
    latency_steps: 0 # float
    down_sample_steps: ${task.obs_down_sample_steps} # int
    rotation_rep: rotation_6d

task_name: &task_name ${name}
dataset_path: example_demo_session/dataset.zarr.zip
pose_repr: &pose_repr
  obs_pose_repr: relative # abs or rel
  action_pose_repr: relative # abs or rel or delta

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

eval_image_transforms:
  - type: CenterCrop
    ratio: 0.95

train_image_transforms: &train_image_transforms
  _target_: umi_day.train_network.common.augmentation.ImageAugmentation
  shape_meta: ${shape_meta}
  transforms:
    - type: RandomCrop
      ratio: 0.95
    - _target_: torchvision.transforms.ColorJitter
      brightness: 0.3
      contrast: 0.4
      saturation: 0.5
      hue: 0.08

dataset:
  _target_: umi_day.train_network.dataset.umi_task_dataset.UmiTaskDataset
  shape_meta: ${shape_meta}
  dataset_path: ${task.dataset_path}
  language_embedding:
    _target_: umi_day.train_network.model.language.language_embedding.LanguageEmbedding
    model_name: "sentence-transformers/sentence-t5-base"
  cache_dir: null
  pose_repr: *pose_repr
  action_padding: true # since we are training multi-task models, we want to pad the actions as to not cut off the ends of each task. In the single-task setting it didn't matter if the ends were cut off since there is usually a reset action at the end of the demonstration where the gripper returns to the starting position. However in the multi-task setting there is likely important actions at the very end of the subtask before transitioning to the next subtask.
  temporally_independent_normalization: False
  max_duration: null
  seed: 42
  val_ratio: 0.05
  include_labels: false
  sample_type: episode
  max_segments: -1
  train_image_augmentation: *train_image_transforms
