# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'umi_day_iphone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for umi_day_iphone
  pod 'Socket.IO-Client-Swift', '~> 16.1.0'

end
